EsimeneMVC/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EsimeneMVC.Models;

namespace EsimeneMVC.Controllers
{
    public class UsersController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();

        // GET: Users
        public ActionResult Index()
        {
            ViewBag.Roles = db.AspNetRoles.ToList();
            return View(db.AspNetUsers.Include("AspNetRoles").ToList());
        }

        public ActionResult AddRole(string id, string roleId)
        {
            AspNetUser u = db.AspNetUsers.Find(id);
            AspNetRole r = db.AspNetRoles.Find(roleId);
            if (u != null && r != null)
            {
                try
                {
                    u.AspNetRoles.Add(r);
                    db.SaveChanges();
                }
                catch { }
            }
            return RedirectToAction("Index");
        }

        public ActionResult RemoveRole(string id, string roleId)
        {
            AspNetUser u = db.AspNetUsers.Find(id);
            AspNetRole r = db.AspNetRoles.Find(roleId);
            if (u != null && r != null)
            {
                try
                {
                    u.AspNetRoles.Remove(r);
                    db.SaveChanges();
                }
                catch { }
            }
            return RedirectToAction("Index");
        }


        // GET: Users/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        public ActionResult CreateContact(string id)
        {
            Contact contact = new Contact { UserId = id };
            return View(contact);
        }

        [HttpPost]
        public ActionResult CreateContact(Contact contact)
        {
            db.Contacts.Add(contact);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = contact.UserId });
        }

        public ActionResult RemoveContact(int id)
        {
            Contact c = db.Contacts.Find(id);
            string userId = c.UserId;
            db.Contacts.Remove(c);
            db.SaveChanges();
            return RedirectToAction("Details", new { id = userId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EsimeneMVC/Views/Users/CreateContact.cshtml
@model EsimeneMVC.Models.Contact

@{
    ViewBag.Title = "CreateContact";
}

<h2>CreateContact</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contact</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @Html.HiddenFor(x => x.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.TYpe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TYpe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TYpe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EsimeneMVC/Views/Users/Details.cshtml
@model EsimeneMVC.Models.AspNetUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AspNetUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DisplayName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lisainfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lisainfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Veelmidagi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Veelmidagi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PictureId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PictureId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<h3>Kontaktandmed:</h3>
<div>
    @foreach (EsimeneMVC.Models.Contact c in Model.Contacts)
    {
        <div class="row">
            <div class="col-lg-2"><p class="form-control">@c.Type</p></div>
            <div class="col-lg-6"><p class="form-control">@c.Data</p></div>
            <div class="col-lg-1">
                @Html.ActionLink("Kustuta", "RemoveContact", new { id = c.Id }, new { @class="btn btn-default"  })
            </div>
        </div>
    }
<div class="row">
    @using (Html.BeginForm("CreateContact", "Users", FormMethod.Post))
    {
        <input type="hidden" name="UserId" value="@Model.Id" /> 
        <div class="col-lg-2"><input type="text" name="Type" class="form-control"/></div>
        <div class="col-lg-6"><input type="text" name="Data" class="form-control" /></div>
        <div class="col-lg-1"><input type="submit" value="Lisa" class="btn btn-default" /></div>
    }
</div>

</div>
@Html.ActionLink("Lisa uus kontakt", "CreateContact", new { id = Model.Id })

EsimeneMVC/Views/Users/Index.cshtml
@model IEnumerable<EsimeneMVC.Models.AspNetUser>
@using EsimeneMVC.Models 
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table" style="background-color:antiquewhite">
    <tr style="background-color:lightgray">
        <th>
            @Html.DisplayNameFor(model => model.DisplayName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>Rollid:</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @foreach (AspNetRole r in ViewBag.Roles)
            {
                if (item.AspNetRoles.Contains(r))
                {
                    @Html.ActionLink(r.Name, "RemoveRole", new { id = item.Id, roleId = r.Id }, new { @class = "btn btn-default", style = "background-color:lightgreen" })
                }
                else
                {
                    @Html.ActionLink(r.Name, "AddRole", new { id = item.Id, roleId = r.Id }, new { @class = "btn btn-default", style = "background-color:pink" })
                }

            }

        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>