EsimeneMVC/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsimeneMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Products = new HashSet<Product>();
            this.CategoryComments = new HashSet<CategoryComment>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryComment> CategoryComments { get; set; }
    }
}

EsimeneMVC/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EsimeneMVC.Models;

namespace EsimeneMVC.Controllers
{
    public class CategoriesController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // kui ma tahaks pilti andmebaasist

        public ActionResult Picture(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            //if (category == null || category.Picture == null || category.Picture.Length == 0)
            if((category?.Picture?.Length??0) == 0)
            {
                return HttpNotFound();
            }
            byte[] pilt = category.Picture;
            if (pilt[0] == 21) pilt = pilt.Skip(78).ToArray();
            return File(pilt, "image/jpg");


        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,CategoryName,Description,Picture")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,CategoryName,Description,Picture")] Category category
            , HttpPostedFileBase file
            )
        {
            
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.Entry(category).Property("Picture").IsModified = false; // vajalik, et ei kustutks olemasolev pilt
                db.SaveChanges();

                if (file != null && file.ContentLength > 0)
                {
                    using (System.IO.BinaryReader br = new System.IO.BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        category.Picture = buff;
                        db.SaveChanges();
                    }


                }

                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddComment(int id, string comment)
        {
            db.Categories.Find(id).CategoryComments.Add(new CategoryComment { Comment = comment });
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EsimeneMVC/Views/Categories/Create.cshtml
@model EsimeneMVC.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EsimeneMVC/Views/Categories/Delete.cshtml
@model EsimeneMVC.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EsimeneMVC/Views/Categories/Details.cshtml
@model EsimeneMVC.Models.Category

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Picture)*@
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CategoryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<h2>Selle kategooria tooted</h2>
<table class="table">
    @Html.ActionLink("Lisa", "Create", "Products", new { categoryId = Model.CategoryID}, new { @class = "btn btn-default" } )
    @foreach (var t in Model.Products)
    {
        <tr>
            <td>@t.ProductID</td>
            <td>@t.ProductName</td>
        </tr>
    }
</table>

EsimeneMVC/Views/Categories/Edit.cshtml
@model EsimeneMVC.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","Categories", FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <img src="@Url.Action("Picture", "Categories", new {id = Model.CategoryID})" />
        <div class="form-group">
            <input type="file" name="file" id="file" class="form-control" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EsimeneMVC/Views/Categories/Index.cshtml
@model IEnumerable<EsimeneMVC.Models.Category>

@{
    ViewBag.Title = "Index";
}
   
<p>@(System.DateTime.Today.Year + 1)</p>
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Picture)
        </th>
        <th>Kommentaarid:</th>
        <th></th>
    </tr>
    <!--see on veebilehel loetav kommentaar-->
    
    @foreach (var item in Model)
    {
        // see on C# kommentaar
        decimal max = item.Products.DefaultIfEmpty().Max(x => x?.UnitPrice??0);
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                <div style="background-color:lightgray;display:block">@Html.DisplayFor(modelItem => item.Description)</div>
                @*siia lisame tooteloetelu - peidame ära*@
                <div id="@($"Kõik{item.CategoryID}")" style="display:none" onclick="vaheta(@item.CategoryID,1)">
                    @foreach (EsimeneMVC.Models.Product p in item.Products)
                    {
                        <p style="color:@(p.UnitPrice == max?"lightcoral":"black")">@($"{p.ProductName} - {p.UnitPrice}")</p>
                        
                        @*<p style="background-color:lightcoral">@p.ProductName - @p.UnitPrice</p>*@
                    }
                </div>
                @*siis lisame teise divi - kus vaid kõige kallim toode*@
                <div id="@($"Üks{item.CategoryID}")" style="display:block;color:lightcoral;background-color:beige" onclick="vaheta(@item.CategoryID,0)">
                    @foreach (EsimeneMVC.Models.Product p in item.Products.OrderByDescending(x => x.UnitPrice).Take(1))
                    {
                        <p>@p.ProductName - @p.UnitPrice</p>
                    }
                </div>
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Picture)*@
                <img src="@Url.Action("Picture", "Categories", new { id = item.CategoryID })" />
            </td>
            <td>
                @foreach(EsimeneMVC.Models.CategoryComment comment in item.CategoryComments)
                {
                    <p>@comment.Comment</p>
                }
                <form action="/Categories/AddComment" method="post">
                    <input name="comment" />
                    <input type="hidden" name="id" value="@item.CategoryID" />
                    <input type="submit" name="Lisa" />
                </form>
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CategoryID }) |
                @Html.ActionLink("Details", "Details", new { id = item.CategoryID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CategoryID })
            </td>
        </tr>
        // see on C#
    }

</table>
<script>
    function vaheta(id, s) {
        var k = document.getElementById("Kõik" + id);
        var y = document.getElementById("Üks" + id);
        if (s == 0) {
            k.style["display"] = "block";
            k.style["backgroundColor"] = "beige";
            y.style["display"] = "none";
        } else {
            y.style["display"] = "block";
            y.style["backgroundColor"] = "beige";
            k.style["display"] = "none";
        }
    }
</script>