TeineMVC/Models/Album.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeineMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Owner { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual DataFile DataFile { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}

TeineMVC/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeineMVC.Models;

namespace TeineMVC.Controllers
{
    

    public class AlbumsController : MyController
    {
        //private NorthwindEntities db = new NorthwindEntities();

        // GET: Albums
        public ActionResult Index()
        {
            var albums = db.Albums; //.Include(a => a.DataFile).Include(a => a.AspNetUser);
            return View(albums.ToList());

        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: Albums/Create
        [Authorize]
        public ActionResult Create()
        {
            //ViewBag.PictureId = new SelectList(db.DataFiles, "Id", "ContentType");
            //ViewBag.Owner = new SelectList(db.AspNetUsers, "Id", "DisplayName");
            return View();
        }
        [Authorize]
        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Album album, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                var aspUser = db.AspNetUsers.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                // see on hetkel sisselogitud kasutaja
                album.Owner = aspUser.Id;
                db.Albums.Add(album);
                db.SaveChanges();

                //if(file != null)
                //{
                //    using (System.IO.BinaryReader br = new System.IO.BinaryReader(file.InputStream))
                //    {
                //        byte[] buff = br.ReadBytes(file.ContentLength);
                //        DataFile f = new DataFile
                //        {
                //            Content = buff,
                //            ContentType = file.ContentType,
                //            FileName = file.FileName.Split('\\').Last().Split('/').Last(),
                //            Created = DateTime.Now
                //        };
                //        db.DataFiles.Add(f);
                //        db.SaveChanges();

                //        album.PictureId = f.Id;
                //        db.SaveChanges();

                //    }

                //}

                SaveDataFile(file, x => album.PictureId = x, null);

                return RedirectToAction("Index");
            }

            //ViewBag.PictureId = new SelectList(db.DataFiles, "Id", "ContentType", album.PictureId);
            //ViewBag.Owner = new SelectList(db.AspNetUsers, "Id", "DisplayName", album.Owner);
            return View(album);
        }

        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
             return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,PictureId")] Album album, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.Entry(album).Property("PictureId").IsModified = false;
                db.Entry(album).Property("Owner").IsModified = false;
                db.SaveChanges();
                
                SaveDataFile(file, x => album.PictureId = x, album.PictureId);

                return RedirectToAction("Index");
            }
             return View(album);
        }

        // GET: Albums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

TeineMVC/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeineMVC.Models;

namespace TeineMVC.Controllers
{
    public class FilesController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();

        // GET: Files
        public ActionResult Index()
        {
            return View(db.DataFiles.ToList());
        }

        // võimaldab mul "vastuseid" hoida meeles
       [OutputCache(VaryByParam = "id", Location = System.Web.UI.OutputCacheLocation.ServerAndClient, Duration = 3600)]
        public ActionResult Content(int? id)
        {
            DataFile f = db.DataFiles.Find(id ?? 0);
            if (f == null) return HttpNotFound();
            return File(f.Content, f.ContentType);
        }

        // GET: Files/Details/5
 
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeineMVC/Views/Albums/Create.cshtml
@model TeineMVC.Models.Album

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Albums", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PictureId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="file" name="file" class="form-control"/>                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TeineMVC/Views/Albums/Delete.cshtml
@model TeineMVC.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFile.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFile.ContentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.DisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.DisplayName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TeineMVC/Views/Albums/Details.cshtml
@model TeineMVC.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataFile.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataFile.ContentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.DisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.DisplayName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TeineMVC/Views/Albums/Edit.cshtml
@model TeineMVC.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Albums", FormMethod.Post, new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Album</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.PictureId)


    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">

        <div class="col-md-10 col-md-offset-2">
            <input type="file" name="file" id="file" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TeineMVC/Views/Albums/Index.cshtml
@model IEnumerable<TeineMVC.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>

        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.DisplayName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @if (item.PictureId != null)
                {
                <img src="@Url.Action("Content", "Files", new { id = item.PictureId })" height="80" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AspNetUser.DisplayName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>